package it.gov.pagopa.reminder.util;

public class Constants {

	public static final String MESSAGE_SCHEMA = "{\r\n"
			+ "  \"name\": \"message\",\r\n"
			+ "  \"type\": \"record\",\r\n"
			+ "  \"namespace\": \"it.gov.pagopa.reminder.dto\",\r\n"
			+ "  \"doc\": \"Kafka JS schema for cosmos api container 'messages'\",\r\n"
			+ "  \"fields\": [\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"op\",\r\n"
			+ "      \"type\": {\r\n"
			+ "        \"type\": \"enum\",\r\n"
			+ "        \"name\": \"MessageCrudOperation\",\r\n"
			+ "        \"symbols\": [\r\n"
			+ "          \"CREATE\",\r\n"
			+ "          \"UPDATE\",\r\n"
			+ "          \"DELETE\"\r\n"
			+ "        ]\r\n"
			+ "      }\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"id\",\r\n"
			+ "      \"type\": \"string\",\r\n"
			+ "      \"default\": \"undefined\"\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"senderServiceId\",\r\n"
			+ "      \"type\": \"string\",\r\n"
			+ "      \"default\": \"undefined\"\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"senderUserId\",\r\n"
			+ "      \"type\": \"string\",\r\n"
			+ "      \"default\": \"undefined\"\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"timeToLiveSeconds\",\r\n"
			+ "      \"type\": \"int\",\r\n"
			+ "      \"default\": 3600\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"createdAt\",\r\n"
			+ "      \"type\": \"long\",\r\n"
			+ "      \"logicalType\": \"timestamp-millis\",\r\n"
			+ "      \"default\": 0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"isPending\",\r\n"
			+ "      \"type\": \"boolean\",\r\n"
			+ "      \"default\": true\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"content_subject\",\r\n"
			+ "      \"type\": \"string\",\r\n"
			+ "      \"default\": \"undefined\"\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"content_type\",\r\n"
			+ "      \"type\": [\"null\", {\r\n"
			+ "        \"type\": \"enum\",\r\n"
			+ "        \"name\": \"MessageContentType\",\r\n"
			+ "        \"symbols\": [\r\n"
			+ "          \"GENERIC\",\r\n"
			+ "          \"PAYMENT\",\r\n"
			+ "          \"EU_COVID_CERT\",\r\n"
			+ "          \"LEGAL\"\r\n"
			+ "        ]\r\n"
			+ "      }],\r\n"
			+ "      \"default\": null\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"content_paymentData_amount\",\r\n"
			+ "      \"type\": \"int\",\r\n"
			+ "      \"default\": 0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"content_paymentData_noticeNumber\",\r\n"
			+ "      \"type\": \"string\",\r\n"
			+ "      \"default\": \"undefined\"\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"content_paymentData_invalidAfterDueDate\",\r\n"
			+ "      \"type\": \"boolean\",\r\n"
			+ "      \"default\": false\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"content_paymentData_payeeFiscalCode\",\r\n"
			+ "      \"type\": \"string\",\r\n"
			+ "      \"default\": \"undefined\"\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"timestamp\",\r\n"
			+ "      \"type\": \"long\",\r\n"
			+ "      \"logicalType\": \"timestamp-millis\",\r\n"
			+ "      \"default\": 0\r\n"
			+ "    }\r\n"
			+ "  ]\r\n"
			+ "}";
	
	public static final String MESSAGE_STATUS_SCHEMA = "{\r\n"
			+ "  \"name\": \"messageStatus\",\r\n"
			+ "  \"type\": \"record\",\r\n"
			+ "  \"namespace\": \"it.gov.pagopa.reminder.dto\",\r\n"
			+ "  \"doc\": \"Kafka JS schema for cosmos api container 'message-status'\",\r\n"
			+ "  \"fields\": [\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"op\",\r\n"
			+ "      \"type\": {\r\n"
			+ "        \"type\": \"enum\",\r\n"
			+ "        \"name\": \"MessageStatusCrudOperation\",\r\n"
			+ "        \"symbols\": [\r\n"
			+ "          \"CREATE\",\r\n"
			+ "          \"UPDATE\",\r\n"
			+ "          \"DELETE\"\r\n"
			+ "        ]\r\n"
			+ "      }\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"id\",\r\n"
			+ "      \"type\": \"string\",\r\n"
			+ "      \"default\": \"undefined\"\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"messageId\",\r\n"
			+ "      \"type\": \"string\",\r\n"
			+ "      \"default\": \"undefined\"\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"version\",\r\n"
			+ "      \"type\": \"int\",\r\n"
			+ "      \"default\": 0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"status\",\r\n"
			+ "      \"type\": {\r\n"
			+ "        \"type\": \"enum\",\r\n"
			+ "        \"name\": \"MessageStatusDescription\",\r\n"
			+ "        \"symbols\": [\r\n"
			+ "          \"ACCEPTED\",\r\n"
			+ "          \"THROTTLED\",\r\n"
			+ "          \"FAILED\",\r\n"
			+ "          \"PROCESSED\",\r\n"
			+ "          \"REJECTED\"\r\n"
			+ "        ]\r\n"
			+ "      }\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"isRead\",\r\n"
			+ "      \"type\": \"boolean\",\r\n"
			+ "      \"default\": false\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"isArchived\",\r\n"
			+ "      \"type\": \"boolean\",\r\n"
			+ "      \"default\": false\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "      \"name\": \"timestamp\",\r\n"
			+ "      \"type\": \"long\",\r\n"
			+ "      \"logicalType\": \"timestamp-millis\",\r\n"
			+ "      \"default\": 0\r\n"
			+ "    }\r\n"
			+ "  ]\r\n"
			+ "}";
	
	public static final String DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ss";
}
