version: '2'

services:
  app:
    image: 'reminder:latest'
    cpus: 1.0
    mem_limit: "3g"
    build:
      context: .
    container_name: app
    ports:
      - 9090:9090
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=200MB
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication
      - HEALTH_VALUE = Reminder-dev-end-var-docker
      - QUARTZ_SCHEDULER_TIMER_NOTIFY=0 * * ? * *
      - REMINDER_MAX=10
      - REMINDER_DAY=0
      - PAYMENT_DAY=0
      - TEST_ACTIVE=false
      - MAX_READ_MESSAGE=10
      - MAX_PAID_MESSAGE=20
      - START_DAY=60
      - SENDER_SERVICE_NAME=Reminder
      - SENDER_ORGANIZATION_NAME=PagoPA
      - SENDER_DEPARTMENT_NAME=AppIO
      - QUARTZ_SCHEDULER_TIMER_NOTIFY=0 /3 * ? * *
      - QUARTZ_SCHEDULER_TIMER_DELETE=0 * * ? * *
      - SCHEDULER_REMINDER_NOTIFY_ACTIVE=true
      - SCHEDULER_REMINDER_DELETE_ACTIVE=false
      - KAFKA_MESSAGE=messages
      - KAFKA_STATUS=message-status
      - KAFKA_PAYMENT=payment-updates
      - KAFKA_SEND=message-reminder-send
      - RESTCALL_INTERVAL_FUNCTION=10000
      - RESTCALL_MAX_ATTEMPTS=3
      - ENABLE_REST_KEY=true
      - IS_ACTIVE_MESSAGE_CONSUMER=true
      - IS_ACTIVE_MESSAGESTATUS_CONSUMER=true
      - IS_ACTIVE_PAYMENT_CONSUMER=true
      - IS_ACTIVE_MESSAGESEND_CONSUMER=true
      - PROXY_ERROR_STATUSCODE=PAA_PAGAMENTO_DUPLICATO,PPT_RPT_DUPLICATA,PPT_PAGAMENTO_DUPLICATO
      - PROXY_ENDPOINT=https://dummy/checkout/auth/payments/v1
      - SECURITY_PROTOCOL_REMINDER=PLAINTEXT
      - SASL_MECHANISM_REMINDER=PLAIN
      - SECURITY_PROTOCOL_SHARED=PLAINTEXT
      - SASL_MECHANISM_SHARED=PLAIN
      - BOOTSTRAP_SERVER_MESSAGESEND=kafka:9092
      - BOOTSTRAP_SERVER_SHARED=kafka:9092
      - BOOTSTRAP_SERVER_MESSAGESTATUS=kafka:9092
      - BOOTSTRAP_SERVER_MESSAGE=kafka:9092
      - MONGO_DATABASE=db
      - IO_NOTIFY_ENDPOINT=https://dummy/service-messages/api/v1
      - PAYMENTUPDATER_ENDPOINT=https://dummy
      - APPLICATIONINSIGHTS_CONNECTION_STRING=appinsights-connection-string
      - MONGO_DATABASE_URI=mongodb://root:root@mongodb:27017
      - KAFKA_URL_MESSAGE=not-required
      - KAFKA_URL_MESSAGESTATUS=not-required
      - KAFKA_URL_MESSAGESEND=not-required
      - KAFKA_URL_SHARED=not-required
      - SASL_JAAS_CONF_SHARED=not-required
      - PROXY_ENDPOINT_SUBSCRIPTION_KEY=dummy
      - PAYMENTUPDATER_ENDPOINT_SUBSCRIPTION_KEY=dummy
      - IO_NOTIFY_ENDPOINT_SUBSCRIPTION_KEY=dummy
    depends_on:
      - mongodb
      - kafka

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  mongodb:
    image: docker.io/bitnami/mongodb:6.0
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=reminder-user
      - MONGODB_PASSWORD=reminder-password
      - MONGODB_DATABASE=db

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data:
    driver: local