version: '2'

services:
  app:
    image: 'reminder:latest'
    cpus: 1.0
    mem_limit: "3g"
    build:
      context: .
    container_name: app
    ports:
      - 9090:9090
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=200MB
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication
      - HEALTH_VALUE = Reminder-dev-end-var-docker
      - QUARTZ_SCHEDULER_TIMER_NOTIFY=0 * * ? * *
