microservice-chart:
  namespace: "messages"
  image:
    repository: "iopcommonacr.azurecr.io/io-premium-reminder-ms"
    tag: "2.3.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: "/api/v1/health/live"
      port: 9090
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: "/api/v1/health/ready"
      port: 9090
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  service:
    create: true
    port: 9090
  ingress:
    create: true
    host: "weubeta.reminder.internal.io.pagopa.it"
    path: "/(api/v1/reminder/.*)"

  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: "70"
  envConfig:
    # required
    WEBSITE_SITE_NAME: "io-p-weubeta-premium-reminder-ms" # required to show cloud role name in application insights
    # app specific

  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: "appinsights-connection-string"
    # app specific
  keyvault:
    name: "io-p-messages-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
