/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.gov.pagopa.reminder.dto.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum MessageFeatureLevelType {
  STANDARD, ADVANCED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MessageFeatureLevelType\",\"namespace\":\"it.gov.pagopa.reminder.dto.avro\",\"symbols\":[\"STANDARD\",\"ADVANCED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
