name: Test CA deployments

on:
  workflow_dispatch:
  push:
    branches:
      - CES-925-migrazione-reminder-su-container-apps

permissions:
  contents: read
  id-token: write
  packages: write
  attestations: write

jobs:
  release:
      uses: pagopa/dx/.github/workflows/container_app_deploy_v1.yaml@CES-958-definire-una-pipeline-di-cd-per-le-container-app
      name: CA Deployment
      secrets: inherit
      with:
        docker_image_description: "no provenance"
        container_app: io-p-itn-com-reminder-ca-01
        resource_group_name: io-p-itn-com-rg-01
        docker_image_name: pagopa/io-premium-reminder-ms
        apply_github_tags_to_image_tags: true
